### ISSUE TITLE
Throws Error "invalid baseUrl" when baseUrl has no port

### ISSUE THREAD

**Issue by sydev** [pmorjan/couchdb-promises#10]
When I use a remote couchdb url, which has no port, it throws this error:

   ```
Error: invalid baseUrl
    at module.exports (/Users/dominik/code/couchdb/node_modules/couchdb-promises/index.js:35:11)
    at __dirname (/Users/dominik/code/couchdb/index.js:6:13)
    at Object.<anonymous> (/Users/dominik/code/couchdb/index.js:10:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

The module should check if there is a port in the baseUrl before checking if its NaN.

**Comment by pmorjan** [comment]
In my opinion a missing port is a programming error and should be handled accordingly.

If you omit the port by mistake then it defaults to port 80. Depending on what's listening on that port you can get a useful error message but you can also ran into a timeout or get an ugly HTML response. 
For simplicity I would like to keep it as it is. WDYT?

**Comment by dsquier** [comment]
Raising an error if there is no port explicitly defined seems reasonable. I'd expect someone to hit this early in development.

An alternative solution could be to default to `5984` if no port is specified..

**Comment by sydev** [comment]
Like @pmorjan said, a missing port should handle as an error, so a default port is unnecessary. But every cloud has a silver lining, I had a positive learning effect 👍

I guess we can close this issue, right?

**Comment by dsquier** [comment]
Yup, close away :)
